version: "3"
services:
  web1:
    build: .
    expose: 
      - 80

  web2:
    build: .
    expose: 
      - 80

  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - web1
      - web2
    ports:
      - "80:80"
      - "70:70"
    expose:
     - "80"
     - "70"
